name: 'Tests Release'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.cc'
      - '**.c'
      - '**.hh'
      - '**.h'
      - '**.axl'
      - '**.arc'
      - '**.config'
  workflow_dispatch:

env:

  SOURCE_DIR: '/__w/arcane-benchs/arcane-benchs/src'
  BUILD_DIR: '/__w/arcane-benchs/arcane-benchs/build'

  # CTest
  CT_RESULT_DIR: '/__w/arcane-benchs/arcane-benchs/test'
  CT_OPTS: "--timeout 2400 --output-on-failure"

  # MPI
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

jobs:
  tests:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/arcane_ubuntu-2404:gcc-14_full_check_latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_DIR }}

      - name: Configure
        shell: bash
        run: |
          cmake \
          -S ${{ env.SOURCE_DIR }} \
          -B ${{ env.BUILD_DIR }} \
          -DCMAKE_BUILD_TYPE=Release \
          -GNinja

      - name: Build
        shell: bash
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Test
        shell: bash
        run: |
          mkdir -p ${{ env.CT_RESULT_DIR }}
          ctest --test-dir ${{ env.BUILD_DIR }} --output-junit ${{ env.CT_RESULT_DIR }}/results.xml ${{ env.CT_OPTS }}

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: tests-artifact
          path: ${{ env.CT_RESULT_DIR }}
          retention-days: 7
